Class {
	#name : 'MgChangeComplementariaAnnouncement',
	#superclass : 'Announcement',
	#instVars : [
		'complementaria'
	],
	#category : 'Web-Milligram-View',
	#package : 'Web-Milligram',
	#tag : 'View'
}

{ #category : 'accessing' }
MgChangeComplementariaAnnouncement >> complementaria [

	^ complementaria
]

{ #category : 'accessing' }
MgChangeComplementariaAnnouncement >> setComplementaria: aBoolean [

	complementaria := aBoolean
]
